on:
  push:
    branches:
      - main

jobs:
  build:
    steps:
      - name: Set FIRST_VAR
        run: echo "FIRST_VAR=value" >> $GITHUB_ENV

      - name: Set SECOND_VAR using FIRST_VAR
        run: echo "SECOND_VAR=${{ env.FIRST_VAR }}-suffix" >> $GITHUB_ENV
