# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    outputs:
      first_var: ${{ steps.set-vars.outputs.first_var }}
      
    steps:
      - name: Set vars
        id: set-vars
        run: echo "first_var=value" >> $GITHUB_OUTPUT

      - name: Use previous output
        run: echo "SECOND_VAR=${{ steps.set-vars.outputs.first_var }}-suffix"
